language: python
sudo: required
dist: xenial

matrix:
  include:
    - python: 3.7

branches:
  only:
    - master
    - dev
    - /^fix-.*$/
    - /^feature-.*$/
    # Regex to build tagged commits with version numbers
    - /\d+\.\d+(\.\d+)?(\S*)?$/

install:
  # -e is important for coverage report
  - pip install sphinx==1.6.7 # the theme not working with sphinx 1.7.0
  - pip install -e .[dev]
  # install win32tools
  - if [ "$MAKE_TESTS" == "true" ]; then
      bash ci/install-win32tools.sh;
      export PATH=${PATH}:${PWD}/win32tools/bin;
      sed -i "s/test_username/${HINET_USERNAME}/" tests/test_*.py;
      sed -i "s/test_password/${HINET_PASSWORD}/" tests/test_*.py;
    fi

after_success:
  - make doc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: docs/_build/html
  on:
    branch: master
    python: '3.7'
    condition: '$BUILD_DOCS == "true"'
