language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install travis-sphinx guzzle_sphinx_theme
  - sed -i "s/test_username/${HINET_USERNAME}/" .travis/install_win32tools.py
  - sed -i "s/test_password/${HINET_PASSWORD}/" .travis/install_win32tools.py
  - python .travis/install_win32tools.py
  - export PATH=${PATH}:${PWD}/win32tools/bin
  - sed -i "s/test_username/${HINET_USERNAME}/" tests/test_*.py
  - sed -i "s/test_password/${HINET_PASSWORD}/" tests/test_*.py

script:
  - cd tests; py.test -v; cd ..
  - travis-sphinx -s docs -b master,docs -n build

after_success:
    - travis-sphinx -b master,docs deploy
