language: python
branch:
  only:
    - travis

install:
    - pip install mkdocs mkdocs-material ghp-import

script:
    - cd docs/
    - mkdocs build --clean --quiet

after_success:
    - ghp-import -b gh-pages -n site -m 'Update by travis'
    - git push "https://${GH_TOKEN}@github.com/seisman/HinetScripts" gh-pages:gh-pages --force --quiet
