language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

branches:
  only:
  - master
  - dev
  - /^fix-.*$/
  - /^feature-.*$/

install:
  # -e is important for coverage report
  - pip install -e .[dev]
  # install win32tools
  - bash ci/install-win32tools.sh
  - export PATH=${PATH}:${PWD}/win32tools/bin

before_script:
  - sed -i "s/test_username/${HINET_USERNAME}/" tests/test_*.py
  - sed -i "s/test_password/${HINET_PASSWORD}/" tests/test_*.py

script:
  - py.test --cov-report term-missing --cov=HinetPy -vs tests/
  - codecov

after_success:
  - bash ci/build-docs.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: docs/_build/html
  on:
    branch: master
    python: '3.6'
