# A GitHub Action to enable "slash commands" in PR comments.
# See https://github.com/peter-evans/slash-command-dispatch

name: Slash Command Dispatch
on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid
    # using to prevent processing unnecessary events.
    #types: [created, edited]
    types: [created]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          commands: black
          issue-type: pull-request
